export enum Permission {
    // General
    VIEW_CHANNEL = "VIEW_CHANNEL",
    MANAGE_SERVER = "MANAGE_SERVER",
    MANAGE_CHANNELS = "MANAGE_CHANNELS",
    MANAGE_ROLES = "MANAGE_ROLES",
    MANAGE_PERMISSIONS = "MANAGE_PERMISSIONS",
    VIEW_AUDIT_LOG = "VIEW_AUDIT_LOG",

    // Members
    KICK_MEMBERS = "KICK_MEMBERS",
    BAN_MEMBERS = "BAN_MEMBERS",
    TIMEOUT_MEMBERS = "TIMEOUT_MEMBERS",
    CHANGE_NICKNAME = "CHANGE_NICKNAME",
    MANAGE_NICKNAMES = "MANAGE_NICKNAMES",

    // Messages
    SEND_MESSAGES = "SEND_MESSAGES",
    SEND_MESSAGES_IN_THREADS = "SEND_MESSAGES_IN_THREADS",
    CREATE_THREADS = "CREATE_THREADS",
    MANAGE_THREADS = "MANAGE_THREADS",
    READ_MESSAGE_HISTORY = "READ_MESSAGE_HISTORY",
    EMBED_LINKS = "EMBED_LINKS",
    ATTACH_FILES = "ATTACH_FILES",
    ADD_REACTIONS = "ADD_REACTIONS",
    USE_EXTERNAL_EMOJIS = "USE_EXTERNAL_EMOJIS",
    MENTION_EVERYONE = "MENTION_EVERYONE",

    // Moderation
    MANAGE_MESSAGES = "MANAGE_MESSAGES",
    DELETE_MESSAGES = "DELETE_MESSAGES",
    PIN_MESSAGES = "PIN_MESSAGES",

    // Voice
    CONNECT = "CONNECT",
    SPEAK = "SPEAK",
    STREAM = "STREAM",
    USE_VOICE_ACTIVITY = "USE_VOICE_ACTIVITY",
    MUTE_MEMBERS = "MUTE_MEMBERS",
    DEAFEN_MEMBERS = "DEAFEN_MEMBERS",
    MOVE_MEMBERS = "MOVE_MEMBERS",

    // Invites
    CREATE_INVITE = "CREATE_INVITE",
    MANAGE_INVITES = "MANAGE_INVITES",

    // Administrator
    ADMINISTRATOR = "ADMINISTRATOR",
}